# Test the ncml handler with the bes.
#


global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

besstandalone_start "ncml/type_validation_tests/byte_bounds.ncml.ddx.bescmd"
compare_stdout "ncml/type_validation_tests/invalid_value.match"  "DAS /data/ncml/type_validation_tests/byte_bounds.ncml" 0 match



