# Test the ncml handler with the bes.
#


global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

besstandalone_start "ncml/fnoc1_improved.ncml.dods.bescmd"
compare_stdout "ncml/fnoc1_improved.ncml.dods.bescmd.baseline" "DataDAS /data/fnoc1_improved.ncml" 0


