# Test the ncml handler with the bes.
# Passthrough test with no transformations or constraints.


global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

besstandalone_start "ncml/nested_passthrough.ncml.ddx.bescmd"
compare_stdout "ncml/nested_passthrough.ncml.ddx.bescmd.baseline" "DDX /data/nested_passthrough.ncml" 0
