#!/bin/sh

# Usage: from the tests subdirectory:
#    ./generate_baselines.sh filename.ncml
# 
# This script is used to run the besstandalone on a particular
# NcML file and save off the DAP responses { das|dds|dods|ddx} 
# into the baselines directory.  It is assumed the caller
# will check these for accuracy before including them in the testsuite.at
# 
# NOTE: It assumes the existence of ../bes-testsuite/bes.conf for running 
# besstandalone properly!  [TODO perhaps relax this to generate bes.conf within here
# as well as we move away from bes-testsuite]
#
# @author mjohnson <m.johnson@opendap.org>

# output filename for the command
BESCMD_FILENAME="test.bescmd"

# input to process to make $BESCMD_FILENAME
TEMPLATE_FILENAME="template.bescmd.in"

# The directory where the data lives, in terms of the bes.conf
DATADIR="/data/ncml" 

# The directory the baselines live in....
BASELINE_DIR="baselines"

# The autogenerated bes.conf which needs to exist! (run make check)
BES_CONF="../bes-testsuite/bes.conf"

# Command to run standalone with the autogenerated bes.conf for the 
# dejagnu testsuite on the autogenerated bescmd file.
RUN_BES="besstandalone -c $BES_CONF -i $BESCMD_FILENAME"

if ! test -e $TEMPLATE_FILENAME
then echo "Fatal error: bescmd template file \"$TEMPLATE_FILENAME\" doesn't exist!"
exit -1
fi

if ! test -e $BES_CONF
then echo "Fatal error: bes conf file \"$BES_CONF\" doesn't exist!"
exit -1
fi

if ! test -d $BASELINE_DIR
then echo "Fatal error: baselines directory \"$BASELINE_DIR\" doesn't exist!"
exit -1;
fi

# Create baselines for all responses....
for response in "das" "dds" "ddx" "dods"
do
    echo "Generating $BESCMD_FILENAME for $DATADIR/$1 response $response...";
    sed -e "s:%ncml_filename%:$DATADIR/$1:" -e "s:%response_type%:$response:" < $TEMPLATE_FILENAME > $BESCMD_FILENAME;
    BASELINE_OUT="$BASELINE_DIR/$1.$response";
    echo "Running besstandalone to generate $BASELINE_OUT...";
    echo "$RUN_BES -f $BASELINE_OUT";
    $RUN_BES -f $BASELINE_OUT;
    echo "";
done

# clean up the temp file
echo "Cleaning up temp file $BESCMD_FILENAME..."
rm -f $BESCMD_FILENAME

