Attributes {
    String Description " joinExisting test on netcdf Grid granules";
    String GranuleFilename "data/nc/simple_test/test_grid_0.nc";
    v {
        time {
            String Description "Test coordinate variable time.";
        }
        v {
            String Description "Test output data array v";
        }
        x {
            String Description "Test coordinate variable x.";
        }
    }
    time {
        String Description "Test coordinate variable time.";
    }
}
