Attributes {
    String Description " joinExisting test on netcdf Grid granules using scan@ncoords";
    v {
        time {
            String Description "Test coordinate variable time.";
        }
        v {
            String Description "Test output data array v";
        }
        x {
            String Description "Test coordinate variable x.";
        }
    }
    time {
        String Description "Test coordinate variable time.";
    }
}
