# Test the ncml handler with the bes.
#


global comp_output		# contains output from besstandalone_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.

besstandalone_start "ncml/types/int32_invalid.ncml.ddx.bescmd"
compare_stdout "ncml/types/invalid_value.match"  "DAS /data/ncml/types/int32_invalid.ncml" 0 match



